// Base de dados para o sistema de estudos de Italiano
// Dividido por níveis e frases diárias

export interface FlashcardSource {
  front: string;
  back: string;
  level: 'basico' | 'avancado';
}

export const ITALIAN_WORDS: FlashcardSource[] = [
  // --- BÁSICO (0-1500) ---
  { front: 'Ciao', back: 'Olá/Tchau', level: 'basico' },
  { front: 'Grazie', back: 'Obrigado(a)', level: 'basico' },
  { front: 'Per favore', back: 'Por favor', level: 'basico' },
  { front: 'Buongiorno', back: 'Bom dia', level: 'basico' },
  { front: 'Buonasera', back: 'Boa noite (chegada)', level: 'basico' },
  { front: 'Prego', back: 'De nada / Por nada', level: 'basico' },
  { front: 'Mi scusi', back: 'Com licença / Desculpe', level: 'basico' },
  { front: 'Acqua', back: 'Água', level: 'basico' },
  { front: 'Pane', back: 'Pão', level: 'basico' },
  { front: 'Vino', back: 'Vinho', level: 'basico' },
  { front: 'Birra', back: 'Cerveja', level: 'basico' },
  { front: 'Muto bene', back: 'Muito bem', level: 'basico' },
  { front: 'Come va?', back: 'Como vai?', level: 'basico' },
  { front: 'Piacere', back: 'Prazer', level: 'basico' },
  { front: 'A presto', back: 'Até logo', level: 'basico' },
  { front: 'Oggi', back: 'Hoje', level: 'basico' },
  { front: 'Domani', back: 'Amanhã', level: 'basico' },
  { front: 'Ieri', back: 'Ontem', level: 'basico' },
  { front: 'Settimana', back: 'Semana', level: 'basico' },
  { front: 'Mese', back: 'Mês', level: 'basico' },
  { front: 'Anno', back: 'Ano', level: 'basico' },
  { front: 'Mangiare', back: 'Comer', level: 'basico' },
  { front: 'Bere', back: 'Beber', level: 'basico' },
  { front: 'Dormire', back: 'Dormir', level: 'basico' },
  { front: 'Camminare', back: 'Caminhar', level: 'basico' },
  { front: 'Correre', back: 'Correr', level: 'basico' },
  { front: 'Parlare', back: 'Falar', level: 'basico' },
  { front: 'Ascoltare', back: 'Ouvir', level: 'basico' },
  { front: 'Guardare', back: 'Olhar/Assistir', level: 'basico' },
  { front: 'Leggere', back: 'Ler', level: 'basico' },
  { front: 'Scrivere', back: 'Escrever', level: 'basico' },
  { front: 'Capire', back: 'Entender', level: 'basico' },
  { front: 'Comprare', back: 'Comprar', level: 'basico' },
  { front: 'Pagare', back: 'Pagar', level: 'basico' },
  { front: 'Andare', back: 'Ir', level: 'basico' },
  { front: 'Venire', back: 'Vir', level: 'basico' },
  { front: 'Tornare', back: 'Voltar', level: 'basico' },
  { front: 'Città', back: 'Cidade', level: 'basico' },
  { front: 'Strada', back: 'Estrada/Rua', level: 'basico' },
  { front: 'Casa', back: 'Casa', level: 'basico' },
  { front: 'Famiglia', back: 'Família', level: 'basico' },
  { front: 'Amico', back: 'Amigo', level: 'basico' },
  { front: 'Lavoro', back: 'Trabalho', level: 'basico' },
  { front: 'Scuola', back: 'Escola', level: 'basico' },
  { front: 'Tempo', back: 'Tempo', level: 'basico' },
  { front: 'Sole', back: 'Sol', level: 'basico' },
  { front: 'Pioggia', back: 'Chuva', level: 'basico' },
  { front: 'Freddo', back: 'Frio', level: 'basico' },
  { front: 'Caldo', back: 'Calor', level: 'basico' },
  { front: 'Bello', back: 'Bonito', level: 'basico' },
  { front: 'Brutto', back: 'Feio', level: 'basico' },
  { front: 'Grande', back: 'Grande', level: 'basico' },
  { front: 'Piccolo', back: 'Pequeno', level: 'basico' },
  { front: 'Nuovo', back: 'Novo', level: 'basico' },
  { front: 'Vecchio', back: 'Velho', level: 'basico' },
  { front: 'Facile', back: 'Fácil', level: 'basico' },
  { front: 'Difficile', back: 'Difícil', level: 'basico' },
  { front: 'Aperto', back: 'Aberto', level: 'basico' },
  { front: 'Chiuso', back: 'Fechado', level: 'basico' },
  { front: 'Velocemente', back: 'Rapidamente', level: 'basico' },
  { front: 'Lentamente', back: 'Lentamente', level: 'basico' },
  { front: 'Sempre', back: 'Sempre', level: 'basico' },
  { front: 'Mai', back: 'Nunca', level: 'basico' },
  { front: 'Spesso', back: 'Frequentemente', level: 'basico' },
  { front: 'Forse', back: 'Talvez', level: 'basico' },
  { front: 'Dove', back: 'Onde', level: 'basico' },
  { front: 'Quando', back: 'Quando', level: 'basico' },
  { front: 'Perché', back: 'Por que / Porque', level: 'basico' },
  { front: 'Chi', back: 'Quem', level: 'basico' },
  { front: 'Come', back: 'Como', level: 'basico' },
  { front: 'Quanto', back: 'Quanto', level: 'basico' },

  // --- AVANÇADO (Após 1500) ---
  { front: 'Ancorché', back: 'Ainda que / Embora', level: 'avancado' },
  { front: 'Affinché', back: 'A fim de que', level: 'avancado' },
  { front: 'Qualora', back: 'Caso / Se por acaso', level: 'avancado' },
  { front: 'Purtuttavia', back: 'Contudo / Não obstante', level: 'avancado' },
  { front: 'Dappertutto', back: 'Em todo lugar / Por toda parte', level: 'avancado' },
  { front: 'Sottosopra', back: 'De cabeça para baixo / Confuso', level: 'avancado' },
  { front: 'Fubbo', back: 'Esperto / Astuto', level: 'avancado' },
  { front: 'Vero e proprio', back: 'Verdadeiro / Real / Autêntico', level: 'avancado' },
  { front: 'Mettercela tutta', back: 'Dar o melhor de si', level: 'avancado' },
  { front: 'Tornare utile', back: 'Ser útil / Vir a calhar', level: 'avancado' },
  { front: 'Fare a meno di', back: 'Ficar sem / Prescindir de', level: 'avancado' },
  { front: 'Prendere in giro', back: 'Zombar / Tirar sarro', level: 'avancado' },
  { front: 'Avere voglia di', back: 'Ter vontade de', level: 'avancado' },
  { front: 'Stare per', back: 'Estar prestes a', level: 'avancado' },
  { front: 'Essere al verde', back: 'Estar sem dinheiro', level: 'avancado' },
  { front: 'Piove a catinelle', back: 'Chove canivetes', level: 'avancado' },
];

export const ITALIAN_EXPRESSIONS = [
  { phrase: 'Dolce far niente', translation: 'A doçura de não fazer nada.', context: 'Famosa expressão que celebra o prazer do descanso e da contemplação.' },
  { phrase: 'In bocca al lupo', translation: 'Boa sorte (literalmente: Na boca do lobo).', context: 'A resposta correta é "Crepi il lupo!" (Que o lobo morra).' },
  { phrase: 'La dolce vita', translation: 'A doce vida.', context: 'Expressão que define um estilo de vida cheio de prazer e luxo.' },
  { phrase: 'Meglio tardi che mai', translation: 'Antes tarde do que nunca.', context: 'Provérbio clássico usado em diversas situações.' },
  { phrase: 'Tutto fumo e niente arrosto', translation: 'Muita fumaça e nenhum assado.', context: 'Referente a algo que parece importante mas não tem substância.' },
  { phrase: 'Chi dorme non piglia pesci', translation: 'Quem dorme não pega peixes.', context: 'Equivalente ao nosso "Quem dorme no ponto..."' },
  { phrase: 'Ogni promessa è debito', translation: 'Toda promessa é uma dívida.', context: 'Usado para reforçar a importância de cumprir o que se promete.' },
  { phrase: 'A caval donato non si guarda in bocca', translation: 'Cavalo dado não se olha os dentes.', context: 'Provérbio sobre ser grato por presentes.' },
  { phrase: 'Non vedo ora', translation: 'Não vejo a hora (Estou ansioso).', context: 'Muito usada para expressar entusiasmo.' },
  { phrase: 'Mettersi nei panni di qualcuno', translation: 'Colocar-se no lugar de alguém.', context: 'Sobre empatia e compreensão.' },
  { phrase: 'Piove sempre sul bagnato', translation: 'Sempre chove no molhado.', context: 'Sobre como a sorte (ou azar) tende a se acumular onde já existe.' },
  { phrase: 'L\'unione fa la forza', translation: 'A união faz a força.', context: 'Clássico sobre colaboração.' },
  { phrase: 'Ognuno è fabbro della sua fortuna', translation: 'Cada um é ferreiro da sua própria sorte.', context: 'Sobre responsabilidade pessoal pelo destino.' },
  { phrase: 'Il tempo vola', translation: 'O tempo voa.', context: 'Sobre a rapidez da vida.' },
  { phrase: 'Sognare ad occhi aperti', translation: 'Sonhar de olhos abertos.', context: 'Sobre devaneios e grandes planos.' },
];
